"""add template_image_style to projects

Revision ID: 5448ecf093b9
Revises: 014
Create Date: 2026-02-19 22:15:19.901246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5448ecf093b9'
down_revision = '014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('template_image_style', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'template_image_style')
    # ### end Alembic commands ###



