"""add tavily_api_key to settings

Revision ID: 7fe426605b8c
Revises: e6a7f776bb7e
Create Date: 2026-04-27 02:17:28.909189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fe426605b8c'
down_revision = 'e6a7f776bb7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('tavily_api_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'tavily_api_key')
    # ### end Alembic commands ###



