"""add lazyllm_api_keys to user_settings

Revision ID: a1cb9099a491
Revises: 6862bd89f1f1
Create Date: 2026-03-05 03:29:25.225340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cb9099a491'
down_revision = '6862bd89f1f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('materials', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'materials', 'users', ['user_id'], ['id'])
    op.drop_column('pages', 'original_pdf_image_path')
    op.alter_column('projects', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'projects', 'users', ['user_id'], ['id'])
    op.drop_column('projects', 'pdf_source_path')
    op.drop_column('projects', 'layout_only')
    op.drop_column('projects', 'template_style_description')
    op.drop_column('projects', 'template_id')
    op.alter_column('reference_files', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'reference_files', 'users', ['user_id'], ['id'])
    op.add_column('user_settings', sa.Column('baidu_api_key', sa.String(length=500), nullable=True))
    op.add_column('user_settings', sa.Column('lazyllm_api_keys', sa.Text(), nullable=True))
    op.drop_column('user_settings', 'baidu_ocr_api_key')
    op.alter_column('user_templates', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_foreign_key(None, 'user_templates', 'users', ['user_id'], ['id'])
    op.drop_column('user_templates', 'style_description')
    op.alter_column('users', 'subscription_plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'free'"))
    op.alter_column('users', 'credits_balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'credits_used_total',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'projects_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'storage_used_mb',
               existing_type=sa.FLOAT(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'ai_calls_this_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index(op.f('ix_users_password_reset_token'), 'users', ['password_reset_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_password_reset_token'), table_name='users')
    op.alter_column('users', 'email_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text("'1'"))
    op.alter_column('users', 'ai_calls_this_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'storage_used_mb',
               existing_type=sa.FLOAT(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'projects_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'credits_used_total',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'credits_balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('users', 'subscription_plan',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'free'"))
    op.add_column('user_templates', sa.Column('style_description', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'user_templates', type_='foreignkey')
    op.alter_column('user_templates', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('user_settings', sa.Column('baidu_ocr_api_key', sa.VARCHAR(length=500), nullable=True))
    op.drop_column('user_settings', 'lazyllm_api_keys')
    op.drop_column('user_settings', 'baidu_api_key')
    op.drop_constraint(None, 'reference_files', type_='foreignkey')
    op.alter_column('reference_files', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('projects', sa.Column('template_id', sa.VARCHAR(length=36), nullable=True))
    op.add_column('projects', sa.Column('template_style_description', sa.TEXT(), nullable=True))
    op.add_column('projects', sa.Column('layout_only', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=True))
    op.add_column('projects', sa.Column('pdf_source_path', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('pages', sa.Column('original_pdf_image_path', sa.VARCHAR(length=500), nullable=True))
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.alter_column('materials', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    # ### end Alembic commands ###



