"""add lazyllm_api_keys to user_settings

Revision ID: a1cb9099a491
Revises: 6862bd89f1f1
Create Date: 2026-03-05 03:29:25.225340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1cb9099a491'
down_revision = '6862bd89f1f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('lazyllm_api_keys', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'lazyllm_api_keys')
    # ### end Alembic commands ###



