"""add baidu_ocr_api_key to settings table

Revision ID: b023c98d4f17
Revises: 38292967f3ca
Create Date: 2026-01-12 22:20:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'b023c98d4f17'
down_revision = '38292967f3ca'
branch_labels = None
depends_on = None


def _column_exists(table_name: str, column_name: str) -> bool:
    """Check if column exists"""
    bind = op.get_bind()
    inspector = inspect(bind)
    columns = [col['name'] for col in inspector.get_columns(table_name)]
    return column_name in columns


def upgrade() -> None:
    """
    Add baidu_ocr_api_key column to settings table.
    
    Idempotent: checks if column exists before adding.
    """
    # ### commands auto generated by Alembic - please adjust! ###
    if not _column_exists('settings', 'baidu_ocr_api_key'):
        op.add_column('settings', sa.Column('baidu_ocr_api_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'baidu_ocr_api_key')
    # ### end Alembic commands ###
